[package]
name = "rust_hive"
version = "0.1.0"
authors = ["Patricio Tula <tula.patricio@gmail.com>", "Julian Mateu <julianmateu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
